const STORAGE_KEY = 'stockroom-state-v1';
const emptyState = { products: [], orders: [], users: [], currentUser: null };

let state = loadState();
let cart = [];
let activeInventoryFilter = 'all';
let activeCategory = 'All';
let alertStream;

function loadState() { return structuredClone(emptyState); }
function saveState() {}
function money(value) { return new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 2 }).format(value); }
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Request failed'); return payload; }
function applyState(serverState) { state = serverState; }
function startAlerts() { if (alertStream) alertStream.close(); if (state.currentUser?.role !== 'Administrator') return; alertStream = new EventSource('/api/events'); alertStream.onmessage = async event => { const payload = JSON.parse(event.data); if (payload.type !== 'sale') return; applyState(await api('/api/state')); renderAll(); toast(`New sale ${payload.order.id}: ${money(payload.order.total)} via ${payload.order.payment}.`); }; }
function dateTime(value) { return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)); }
function initials(name) { return name.split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase(); }
function getProduct(id) { return state.products.find(product => product.id === id); }
function revenue() { return state.orders.reduce((sum, order) => sum + order.total, 0); }
function lowStock() { return state.products.filter(product => product.stock <= product.reorder); }

function showApp() {
  document.getElementById('login-screen').hidden = true;
  document.getElementById('app-shell').hidden = false;
  const user = state.currentUser;
  document.getElementById('sidebar-name').textContent = user.name;
  document.getElementById('sidebar-role').textContent = user.role;
  document.getElementById('sidebar-avatar').textContent = user.initials;
  document.getElementById('greeting-name').textContent = user.role === 'Administrator' ? 'admin' : user.name.split(' ')[0];
  document.querySelectorAll('.admin-only').forEach(element => { element.hidden = user.role !== 'Administrator'; });
  startAlerts();
  renderAll();
}

function renderAll() { renderOverview(); renderInventory(); renderPos(); renderOrders(); renderTeam(); renderReports(); updateDate(); }
function updateDate() { document.getElementById('today-date').textContent = new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric' }).format(new Date()); }
function metricCard(label, value, change, down = false) { const details = { 'TOTAL REVENUE': 'Money received from completed sales.', ORDERS: 'Number of completed customer transactions.', 'ITEMS IN STOCK': 'Total units currently available to sell.', 'AVG. ORDER VALUE': 'Average amount paid per completed order.', 'GROSS SALES': 'Total value of all completed sales.', 'COMPLETED ORDERS': 'Sales successfully processed through the register.', REFUNDS: 'Money returned to customers during this period.', 'TODAY\'S SALES': 'Sales completed since midnight.', 'THIS MONTH': 'Sales completed since the first day of this month.', 'THIS YEAR': 'Sales completed since January 1.', 'AVERAGE ORDER': 'Average value of completed orders.', 'UNITS SOLD': 'Total product units sold.', 'STOCK VALUE': 'Current selling value of available stock.' }; return `<div class="metric-card"><span class="metric-label">${label}</span><strong>${value}</strong><span class="metric-change ${down ? 'down' : ''}">${change}</span><small class="metric-detail">${details[label] || 'Current business performance measure.'}</small></div>`; }

function renderOverview() {
  const total = revenue();
  const stockMetric = metricCard('ITEMS IN STOCK', state.products.reduce((sum, product) => sum + product.stock, 0), `${lowStock().length} need attention`, true);
  document.getElementById('overview-metrics').innerHTML = state.currentUser.role === 'Administrator' ? [metricCard('TOTAL REVENUE', money(total), '+12.8% vs last week'), metricCard('ORDERS', state.orders.length.toString(), '+8.2% vs last week'), stockMetric, metricCard('AVG. ORDER VALUE', money(state.orders.length ? total / state.orders.length : 0), '+4.1% vs last week')].join('') : stockMetric;
  document.getElementById('low-stock-badge').textContent = lowStock().length;
  document.getElementById('low-stock-list').innerHTML = lowStock().slice(0, 4).map(product => `<div class="compact-item"><i class="stock-indicator"></i><div class="compact-copy"><strong>${product.name}</strong><span>Reorder at ${product.reorder} units</span></div><span class="stock-count">${product.stock} left</span></div>`).join('') || '<div class="empty-state">All products are well stocked.</div>';
  document.getElementById('activity-list').innerHTML = state.orders.slice(0, 4).map(order => `<div class="activity-item"><span class="activity-icon">₦</span><div class="activity-copy"><strong>${order.staff} completed ${order.id}</strong><span>${dateTime(order.date)} · ${order.payment}</span></div><span class="activity-amount">${money(order.total)}</span></div>`).join('');
  document.getElementById('on-shift-list').innerHTML = state.users.filter(user => user.status === 'Active').map(user => `<div class="shift-item"><div class="avatar" style="background:${user.color}">${user.initials}</div><div class="shift-name"><strong>${user.name}</strong><small>${user.role}</small></div><span class="shift-status">ACTIVE</span></div>`).join('');
  const cash = state.orders.filter(order => order.payment === 'Cash').reduce((sum, order) => sum + order.total, 0);
  const card = state.orders.filter(order => order.payment === 'Card').reduce((sum, order) => sum + order.total, 0);
  document.getElementById('cash-drawer').textContent = money(cash); document.getElementById('cash-sales').textContent = money(cash); document.getElementById('card-sales').textContent = money(card);
  const chart = Array(7).fill(0); state.orders.slice(0, 7).forEach((order, index) => { chart[6 - index] = order.total; });
  document.getElementById('sales-chart').innerHTML = state.orders.length ? chart.map((value, index) => `<div class="bar-group"><i class="bar secondary" style="height:${Math.max(8, value * .025)}%"></i><i class="bar" style="height:${Math.max(8, value * .034)}%"></i><span class="bar-label">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][index]}</span></div>`).join('') : '<div class="empty-state">No sales yet. Complete a sale to see revenue here.</div>';
}

function renderInventory() {
  const search = (document.getElementById('inventory-search')?.value || '').toLowerCase();
  const filtered = state.products.filter(product => { const matchesText = `${product.name} ${product.sku} ${product.category}`.toLowerCase().includes(search); return matchesText && (activeInventoryFilter === 'all' || product.stock <= product.reorder); });
  document.getElementById('all-count').textContent = state.products.length; document.getElementById('low-count').textContent = lowStock().length;
  document.getElementById('inventory-table').innerHTML = filtered.map(product => `<tr><td><div class="product-cell"><span class="product-thumb">${product.icon}</span>${product.name}</div></td><td class="sku">${product.sku}</td><td class="table-muted">${product.category}</td><td>${money(product.price)}</td><td class="${product.stock <= product.reorder ? 'stock-low' : 'stock-good'}">${product.stock} units</td><td><span class="status-pill ${product.stock <= product.reorder ? 'warning' : 'success'}">${product.stock <= product.reorder ? 'Reorder' : 'In stock'}</span></td><td><button class="table-action admin-only" data-adjust="${product.id}" title="Adjust stock">...</button></td></tr>`).join('');
  document.getElementById('inventory-empty').hidden = filtered.length > 0;
  document.querySelectorAll('.admin-only').forEach(element => { element.hidden = state.currentUser?.role !== 'Administrator'; });
}

function renderPos() {
  const categories = ['All', ...new Set(state.products.map(product => product.category))];
  document.getElementById('category-tabs').innerHTML = categories.map(category => `<button class="category-tab ${category === activeCategory ? 'active' : ''}" data-category="${category}">${category}</button>`).join('');
  const search = (document.getElementById('pos-search')?.value || '').toLowerCase();
  const products = state.products.filter(product => (activeCategory === 'All' || product.category === activeCategory) && product.name.toLowerCase().includes(search));
  document.getElementById('pos-product-grid').innerHTML = products.map(product => `<button class="pos-product" data-add-cart="${product.id}" ${product.stock === 0 ? 'disabled' : ''}><span class="pos-product-image">${product.icon}</span><strong>${product.name}</strong><small>${product.category} · ${product.stock} available</small><span class="pos-product-bottom"><b>${money(product.price)}</b><span>${product.stock ? '+ Add' : 'Out'}</span></span></button>`).join('');
  renderCart();
}

function renderCart() {
  const quantity = cart.reduce((sum, line) => sum + line.quantity, 0); const total = cart.reduce((sum, line) => sum + getProduct(line.productId).price * line.quantity, 0);
  document.getElementById('cart-count').textContent = quantity; document.getElementById('cart-subtotal').textContent = money(total); document.getElementById('cart-total').textContent = money(total); document.getElementById('charge-total').textContent = money(total); document.getElementById('checkout-button').disabled = !cart.length;
  document.getElementById('cart-items').innerHTML = cart.length ? cart.map(line => { const product = getProduct(line.productId); return `<div class="cart-line"><div class="cart-line-info"><strong>${product.name}</strong><small>${money(product.price)} each</small><div class="qty-control"><button data-qty="${product.id}" data-change="-1">-</button><span>${line.quantity}</span><button data-qty="${product.id}" data-change="1">+</button></div></div><span class="cart-line-total">${money(product.price * line.quantity)}</span></div>`; }).join('') : '<div class="cart-empty"><span>+</span><strong>Your cart is empty</strong><p>Select products to start a sale.</p></div>';
}

function renderOrders() {
  const total = revenue(); document.getElementById('order-metrics').innerHTML = [metricCard('GROSS SALES', money(total), 'Across all completed orders'), metricCard('COMPLETED ORDERS', state.orders.length, 'All registers'), metricCard('REFUNDS', money(0), 'No refunds this period')].join('');
  document.getElementById('orders-table').innerHTML = state.orders.map(order => `<tr><td class="sku">${order.id}</td><td class="table-muted">${dateTime(order.date)}</td><td>${order.customer}</td><td>${order.staff}</td><td><span class="status-pill">${order.payment}</span></td><td><strong>${money(order.total)}</strong></td><td><span class="status-pill success">Completed</span></td></tr>`).join(''); document.getElementById('orders-empty').hidden = state.orders.length > 0;
}

function renderTeam() { document.getElementById('team-grid').innerHTML = state.users.map(user => `<div class="team-card"><div class="team-card-head"><div class="avatar" style="background:${user.color}">${user.initials}</div><div><h3>${user.name}</h3><p>${user.role}</p></div></div><div class="team-card-row"><span>Status</span><strong class="${user.status === 'Active' ? 'shift-status' : 'table-muted'}">${user.status}</strong></div><div class="team-card-row"><span>Username</span><span class="table-muted">${user.username}</span></div>${user.role === 'Administrator' ? '' : `<button class="secondary-button team-action" data-toggle-user="${user.id}" data-next-status="${user.status === 'Active' ? 'Inactive' : 'Active'}">${user.status === 'Active' ? 'Deactivate worker' : 'Activate worker'}</button>`}</div>`).join(''); }
function renderReports() { const reports = state.reports || { daily: { sales: 0, orders: 0 }, monthly: { sales: 0, orders: 0 }, yearly: { sales: 0, orders: 0 }, unitsSold: 0, stockUnits: 0, stockValue: 0 }; const average = reports.all?.orders ? reports.all.sales / reports.all.orders : 0; document.getElementById('report-metrics').innerHTML = [metricCard('TODAY\'S SALES', money(reports.daily.sales), `${reports.daily.orders} completed orders`), metricCard('THIS MONTH', money(reports.monthly.sales), `${reports.monthly.orders} completed orders`), metricCard('THIS YEAR', money(reports.yearly.sales), `${reports.yearly.orders} completed orders`), metricCard('AVERAGE ORDER', money(average), `${reports.all?.orders || 0} orders measured`), metricCard('UNITS SOLD', reports.unitsSold, 'All completed orders'), metricCard('STOCK VALUE', money(reports.stockValue), `${reports.stockUnits} units currently held`)].join(''); const productSales = {}; state.orders.forEach(order => order.items.forEach(item => { productSales[item.productId] = (productSales[item.productId] || 0) + item.quantity; })); const ranked = Object.entries(productSales).sort((a,b) => b[1] - a[1]).slice(0, 5); document.getElementById('top-products').innerHTML = ranked.length ? ranked.map(([id, count], index) => { const product = getProduct(Number(id)); return `<div class="ranked-item"><span class="rank-number">0${index + 1}</span><div class="ranked-info"><strong>${product?.name || 'Deleted product'}</strong><small>${count} units sold</small></div><span class="ranked-value">${product ? money(product.price * count) : '-'}</span></div>`; }).join('') : '<div class="empty-state">No completed sales to audit yet.</div>'; const paymentMethods = [...new Set(state.orders.map(order => order.payment))]; const totalOrders = Math.max(state.orders.length, 1); document.getElementById('payment-mix').innerHTML = paymentMethods.length ? paymentMethods.map(label => { const count = state.orders.filter(order => order.payment === label).length; return `<div class="payment-row"><div class="payment-row-head"><span>${label}</span><strong>${Math.round(count / totalOrders * 100)}%</strong></div><div class="payment-bar"><span style="width:${Math.max(2, count / totalOrders * 100)}%"></span></div></div>`; }).join('') : '<div class="empty-state">Payment mix will appear after the first sale.</div>'; }

function openModal(content) { document.getElementById('modal-root').innerHTML = `<div class="modal-backdrop" data-close-modal><div class="modal">${content}</div></div>`; }
function closeModal() { document.getElementById('modal-root').innerHTML = ''; }
function toast(message) { const element = document.getElementById('toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2600); }
function switchView(view) { const user = state.currentUser; if (['team', 'reports'].includes(view) && user.role !== 'Administrator') { toast('Admin access is required for this area.'); return; } document.querySelectorAll('.view').forEach(section => section.classList.toggle('active-view', section.id === `view-${view}`)); document.querySelectorAll('.nav-item[data-view]').forEach(button => button.classList.toggle('active', button.dataset.view === view)); const titles = { overview: 'Overview', inventory: 'Inventory', pos: 'Point of sale', orders: 'Orders', team: 'Team', reports: 'Reports' }; document.getElementById('page-title').textContent = titles[view]; document.querySelector('.sidebar')?.classList.remove('open'); }

document.addEventListener('click', event => {
  const viewButton = event.target.closest('[data-view], [data-view-target]'); if (viewButton) switchView(viewButton.dataset.view || viewButton.dataset.viewTarget);
  const category = event.target.closest('[data-category]'); if (category) { activeCategory = category.dataset.category; renderPos(); }
  const add = event.target.closest('[data-add-cart]'); if (add) { const product = getProduct(Number(add.dataset.addCart)); const line = cart.find(item => item.productId === product.id); if (line) { if (line.quantity < product.stock) line.quantity += 1; } else cart.push({ productId: product.id, quantity: 1 }); renderCart(); }
  const qty = event.target.closest('[data-qty]'); if (qty) { const line = cart.find(item => item.productId === Number(qty.dataset.qty)); line.quantity += Number(qty.dataset.change); if (line.quantity <= 0) cart = cart.filter(item => item !== line); if (line.quantity > getProduct(line.productId).stock) line.quantity = getProduct(line.productId).stock; renderCart(); }
  const toggleUser = event.target.closest('[data-toggle-user]'); if (toggleUser) { api(`/api/users/${toggleUser.dataset.toggleUser}`, { method: 'PATCH', body: JSON.stringify({ status: toggleUser.dataset.nextStatus }) }).then(async () => { applyState(await api('/api/state')); renderAll(); toast(`Worker account ${toggleUser.dataset.nextStatus === 'Active' ? 'activated' : 'deactivated'}.`); }).catch(error => toast(error.message)); }
  const adjust = event.target.closest('[data-adjust]'); if (adjust) { const product = getProduct(Number(adjust.dataset.adjust)); openModal(`<div class="modal-head"><div><p class="eyebrow">INVENTORY ADJUSTMENT</p><h2>${product.name}</h2></div><button class="close-button" data-close-modal>x</button></div><form id="adjust-form"><label>Current stock<input value="${product.stock} units" disabled></label><label>New stock<input id="new-stock" type="number" min="0" value="${product.stock}" required></label><div class="modal-actions"><button type="button" class="secondary-button" data-close-modal>Cancel</button><button class="primary-button">Update stock</button></div></form>`); document.getElementById('adjust-form').addEventListener('submit', async e => { e.preventDefault(); await api(`/api/products/${product.id}`, { method: 'PATCH', body: JSON.stringify({ stock: Number(document.getElementById('new-stock').value) }) }); applyState(await api('/api/state')); closeModal(); renderAll(); toast(`${product.name} stock updated.`); }); }
  if (event.target.matches('[data-close-modal]')) closeModal();
});

document.getElementById('login-form').addEventListener('submit', async event => { event.preventDefault(); const username = document.getElementById('login-username').value.trim().toLowerCase(); const password = document.getElementById('login-password').value; try { applyState(await api('/api/login', { method: 'POST', body: JSON.stringify({ username, password }) })); showApp(); } catch { document.getElementById('login-error').hidden = false; } });
document.getElementById('logout-button').addEventListener('click', async () => { alertStream?.close(); await api('/api/logout', { method: 'POST' }); state.currentUser = null; location.reload(); });
document.getElementById('inventory-search').addEventListener('input', renderInventory); document.getElementById('pos-search').addEventListener('input', renderPos); document.getElementById('clear-cart').addEventListener('click', () => { cart = []; renderCart(); });
document.querySelectorAll('.filter-button').forEach(button => button.addEventListener('click', () => { activeInventoryFilter = button.dataset.filter; document.querySelectorAll('.filter-button').forEach(item => item.classList.toggle('active', item === button)); renderInventory(); }));
document.getElementById('checkout-button').addEventListener('click', () => { const total = cart.reduce((sum, line) => sum + getProduct(line.productId).price * line.quantity, 0); openModal(`<div class="modal-head"><div><p class="eyebrow">COMPLETE SALE</p><h2>Payment method</h2></div><button class="close-button" data-close-modal>x</button></div><p class="muted">Total due: <strong>${money(total)}</strong></p><form id="payment-form"><label>Payment method<select id="payment-method"><option>Card</option><option>Cash</option><option>Transfer</option></select></label><label>Customer name (optional)<input id="customer-name" placeholder="Walk-in customer"></label><div class="modal-actions"><button type="button" class="secondary-button" data-close-modal>Cancel</button><button class="primary-button">Complete sale <span>-></span></button></div></form>`); document.getElementById('payment-form').addEventListener('submit', async event => { event.preventDefault(); try { applyState(await api('/api/orders', { method: 'POST', body: JSON.stringify({ customer: document.getElementById('customer-name').value || 'Walk-in customer', payment: document.getElementById('payment-method').value, items: cart }) })); cart = []; closeModal(); renderAll(); switchView('orders'); toast('Sale completed and inventory updated.'); } catch (error) { toast(error.message); } }); });
document.getElementById('add-product-button').addEventListener('click', () => { openModal(`<div class="modal-head"><div><p class="eyebrow">CATALOG</p><h2>Add product</h2></div><button class="close-button" data-close-modal>x</button></div><form id="product-form" class="modal-form"><label class="full-field">Product name<input id="product-name" required placeholder="e.g. Oak Serving Board"></label><label>SKU<input id="product-sku" required placeholder="HP-072"></label><label>Category<input id="product-category" required placeholder="Home"></label><label>Price in naira<input id="product-price" type="number" min="0" step="0.01" required placeholder="24000"></label><label>Opening stock<input id="product-stock" type="number" min="0" required placeholder="10"></label><label>Reorder point<input id="product-reorder" type="number" min="0" required value="5"></label><div class="modal-actions full-field"><button type="button" class="secondary-button" data-close-modal>Cancel</button><button class="primary-button">Add product</button></div></form>`); document.getElementById('product-form').addEventListener('submit', async event => { event.preventDefault(); const name = document.getElementById('product-name').value; try { applyState(await api('/api/products', { method: 'POST', body: JSON.stringify({ name, sku: document.getElementById('product-sku').value, category: document.getElementById('product-category').value, price: Number(document.getElementById('product-price').value), stock: Number(document.getElementById('product-stock').value), reorder: Number(document.getElementById('product-reorder').value), icon: initials(name) }) })); closeModal(); renderAll(); toast(`${name} added to inventory.`); } catch (error) { toast(error.message); } }); });
document.getElementById('invite-button').addEventListener('click', () => { openModal(`<div class="modal-head"><div><p class="eyebrow">TEAM ACCESS</p><h2>Create worker account</h2></div><button class="close-button" data-close-modal>x</button></div><p class="muted">Set the worker's login details directly. No email invitation is sent.</p><form id="worker-form" class="modal-form"><label class="full-field">Worker name<input id="worker-name" required placeholder="e.g. Jordan Blake"></label><label>Username<input id="worker-username" required pattern="[A-Za-z0-9._-]+" placeholder="jordan"></label><label>Password<input id="worker-password" type="password" minlength="6" required placeholder="At least 6 characters"></label><div class="modal-actions full-field"><button type="button" class="secondary-button" data-close-modal>Cancel</button><button class="primary-button">Create account</button></div></form>`); document.getElementById('worker-form').addEventListener('submit', async event => { event.preventDefault(); const name = document.getElementById('worker-name').value.trim(); const username = document.getElementById('worker-username').value.trim().toLowerCase(); const password = document.getElementById('worker-password').value; try { applyState(await api('/api/users', { method: 'POST', body: JSON.stringify({ name, username, password }) })); closeModal(); renderAll(); toast(`${name} can now sign in as ${username}.`); } catch (error) { toast(error.message.includes('UNIQUE') ? 'That username is already in use.' : error.message); } }); });
document.getElementById('reset-data-button').addEventListener('click', async () => { if (!confirm('Reset all products, stock, orders, and audit data? The administrator account will remain.')) return; try { applyState(await api('/api/reset', { method: 'POST' })); cart = []; renderAll(); switchView('overview'); toast('Business data reset. The workspace is ready for new records.'); } catch (error) { toast(error.message); } });
document.getElementById('export-orders').addEventListener('click', () => { const header = 'Order,Date,Customer,Staff,Payment,Total,Status'; const rows = state.orders.map(order => [order.id, order.date, order.customer, order.staff, order.payment, order.total.toFixed(2), 'Completed'].map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')); const blob = new Blob([[header, ...rows].join('\n')], { type: 'text/csv' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `stockroom-orders-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); toast('Orders CSV downloaded.'); });
document.getElementById('mobile-menu').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open'));
api('/api/state').then(serverState => { applyState(serverState); showApp(); }).catch(() => {});