let securityState = { events: [], failedByUsername: [], activeSessions: [] };
let securityStream;
const $ = selector => document.querySelector(selector);
function escapeText(value) { const element = document.createElement('span'); element.textContent = value ?? ''; return element.innerHTML; }
function time(value) { return new Intl.DateTimeFormat('en-NG', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', second: '2-digit' }).format(new Date(value)); }
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
function render() { $('#active-visitors').textContent = securityState.activeVisitors; $('#failed-logins').textContent = securityState.failedLogins; $('#successful-logins').textContent = securityState.successfulLogins; $('#total-events').textContent = securityState.totalEvents; $('#last-updated').textContent = `Updated ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`; $('#session-count').textContent = `${securityState.activeSessions.length} sessions`; $('#security-events').innerHTML = securityState.events.length ? securityState.events.map(event => `<div class="security-event"><span class="event-kind ${event.type === 'login_failed' ? 'failed' : event.type === 'login_success' ? 'success' : ''}">${event.type.replaceAll('_', ' ').toUpperCase()}</span><div class="event-copy"><strong>${escapeText(event.username)}</strong><small>${escapeText(event.ip)} · ${escapeText(event.details)}</small></div><span class="event-time">${time(event.createdAt)}</span></div>`).join('') : '<div class="security-empty">No security events recorded yet.</div>'; $('#failed-by-user').innerHTML = securityState.failedByUsername.length ? securityState.failedByUsername.map(row => `<div class="failed-row"><span>${escapeText(row.username)}</span><strong>${row.count}</strong></div>`).join('') : '<div class="security-empty">No failed attempts.</div>'; $('#active-sessions').innerHTML = securityState.activeSessions.length ? securityState.activeSessions.map(session => `<div class="session-card"><strong>${escapeText(session.username)}</strong><small>${escapeText(session.role)}<br>${escapeText(session.ip)}<br>seen ${time(session.lastSeen)}</small></div>`).join('') : '<div class="security-empty">No active company sessions.</div>'; }
function toast(message) { const element = $('#security-toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 3000); }
async function refresh() { securityState = await api('/api/security/state'); render(); }
function connectStream() { securityStream = new EventSource('/api/security/events'); securityStream.onmessage = async event => { const data = JSON.parse(event.data); if (data.type === 'connected') return; await refresh(); toast(`${data.type.replaceAll('_', ' ')} · ${data.username}`); }; securityStream.onerror = () => { securityStream.close(); setTimeout(connectStream, 5000); }; }
$('#security-logout').addEventListener('click', async () => { securityStream?.close(); await api('/api/logout', { method: 'POST' }); location.href = '/'; });
refresh().then(connectStream).catch(() => { location.href = '/'; });
setInterval(refresh, 30000);
