const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const db = new DatabaseSync(process.env.DB_PATH || path.join(ROOT, 'stockroom.db'));
const sessions = new Map();
const adminStreams = new Set();
const securityStreams = new Set();

function hashPassword(password) { return crypto.scryptSync(password, 'stockroom-local-salt', 32).toString('hex'); }
function json(response, status, payload) { response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(payload)); }
function readBody(request) { return new Promise((resolve, reject) => { let body = ''; request.on('data', chunk => { body += chunk; if (body.length > 1e6) request.destroy(); }); request.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch (error) { reject(error); } }); request.on('error', reject); }); }
function clientIp(request) { return (request.headers['x-forwarded-for'] || request.socket.remoteAddress || 'unknown').split(',')[0].trim(); }
function userFromRequest(request) { const token = (request.headers.cookie || '').split(';').map(item => item.trim()).find(item => item.startsWith('stockroom_session='))?.split('=')[1]; const session = token ? sessions.get(token) : null; if (session) session.lastSeen = Date.now(); return session?.user || null; }
function requireUser(request, response, admin = false) { const user = userFromRequest(request); if (!user) { json(response, 401, { error: 'Authentication required' }); return null; } if (user.role === 'Super administrator' || (admin && user.role !== 'Administrator')) { json(response, 403, { error: 'Company workspace access required' }); return null; } return user; }
function requireSecurity(request, response) { const user = userFromRequest(request); if (!user) { json(response, 401, { error: 'Authentication required' }); return null; } if (user.role !== 'Super administrator') { json(response, 403, { error: 'Security console access required' }); return null; } return user; }
function safeUser(user) { return { id: user.id, name: user.name, username: user.username, role: user.role, initials: user.initials, status: user.status, color: user.color }; }
function recordSecurity(type, request, username, details = '') { db.prepare('INSERT INTO security_events (event_type, username, ip, user_agent, details, created_at) VALUES (?, ?, ?, ?, ?, ?)').run(type, username || 'unknown', clientIp(request), request.headers['user-agent'] || 'unknown', details, new Date().toISOString()); broadcastSecurity({ type, username: username || 'unknown', ip: clientIp(request), details, createdAt: new Date().toISOString() }); }

function initializeDatabase() {
  db.exec(`
    PRAGMA foreign_keys = ON;
    CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, username TEXT NOT NULL UNIQUE, email TEXT, password_hash TEXT NOT NULL, role TEXT NOT NULL, initials TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Active', color TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, sku TEXT NOT NULL UNIQUE, category TEXT NOT NULL, price_kobo INTEGER NOT NULL, stock INTEGER NOT NULL DEFAULT 0, reorder INTEGER NOT NULL DEFAULT 5, icon TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT, order_number TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, customer TEXT NOT NULL, staff_user_id INTEGER NOT NULL, payment TEXT NOT NULL, total_kobo INTEGER NOT NULL, FOREIGN KEY (staff_user_id) REFERENCES users(id));
    CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity INTEGER NOT NULL, unit_price_kobo INTEGER NOT NULL, FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, FOREIGN KEY (product_id) REFERENCES products(id));
    CREATE TABLE IF NOT EXISTS security_events (id INTEGER PRIMARY KEY AUTOINCREMENT, event_type TEXT NOT NULL, username TEXT NOT NULL, ip TEXT NOT NULL, user_agent TEXT NOT NULL, details TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
  `);
  if (db.prepare("SELECT COUNT(*) AS count FROM users WHERE role = 'Administrator'").get().count === 0) {
    const addUser = db.prepare('INSERT INTO users (name, username, email, password_hash, role, initials, status, color) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
    addUser.run('Administrator', 'admin', 'admin@stockroom.local', hashPassword('admin123'), 'Administrator', 'AD', 'Active', '#e8b960');
  }
  if (db.prepare("SELECT COUNT(*) AS count FROM users WHERE role = 'Super administrator'").get().count === 0) {
    const addUser = db.prepare('INSERT INTO users (name, username, email, password_hash, role, initials, status, color) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
    addUser.run('Security Console', process.env.SUPER_ADMIN_USERNAME || '\"\"\"\"', 'security@internal.local', hashPassword(process.env.SUPER_ADMIN_PASSWORD || "...///''''"), 'Super administrator', 'SC', 'Active', '#b9f6d0');
  }
}
function product(row) { return { id: row.id, name: row.name, sku: row.sku, category: row.category, price: row.price_kobo / 100, stock: row.stock, reorder: row.reorder, icon: row.icon }; }
function getProducts() { return db.prepare('SELECT * FROM products ORDER BY id').all().map(product); }
function getOrders() { const orders = db.prepare(`SELECT o.*, u.name AS staff FROM orders o JOIN users u ON u.id = o.staff_user_id ORDER BY o.id DESC`).all(); const items = db.prepare('SELECT product_id AS productId, quantity, order_id FROM order_items').all(); return orders.map(order => ({ id: order.order_number, date: order.created_at, customer: order.customer, staff: order.staff, payment: order.payment, total: order.total_kobo / 100, items: items.filter(item => item.order_id === order.id).map(({ productId, quantity }) => ({ productId, quantity })) })); }
function getUsers() { return db.prepare('SELECT * FROM users ORDER BY id').all().map(safeUser); }
function getReports() { const sales = db.prepare(`SELECT COALESCE(SUM(total_kobo), 0) AS totalKobo, COUNT(*) AS orders FROM orders`).get(); const daily = db.prepare(`SELECT COALESCE(SUM(total_kobo), 0) AS totalKobo, COUNT(*) AS orders FROM orders WHERE date(created_at) = date('now', 'localtime')`).get(); const monthly = db.prepare(`SELECT COALESCE(SUM(total_kobo), 0) AS totalKobo, COUNT(*) AS orders FROM orders WHERE strftime('%Y-%m', created_at, 'localtime') = strftime('%Y-%m', 'now', 'localtime')`).get(); const yearly = db.prepare(`SELECT COALESCE(SUM(total_kobo), 0) AS totalKobo, COUNT(*) AS orders FROM orders WHERE strftime('%Y', created_at, 'localtime') = strftime('%Y', 'now', 'localtime')`).get(); const units = db.prepare(`SELECT COALESCE(SUM(quantity), 0) AS units FROM order_items`).get().units; const stock = db.prepare(`SELECT COALESCE(SUM(stock), 0) AS units, COALESCE(SUM(stock * price_kobo), 0) AS valueKobo FROM products`).get(); return { all: { sales: sales.totalKobo / 100, orders: sales.orders }, daily: { sales: daily.totalKobo / 100, orders: daily.orders }, monthly: { sales: monthly.totalKobo / 100, orders: monthly.orders }, yearly: { sales: yearly.totalKobo / 100, orders: yearly.orders }, unitsSold: units, stockUnits: stock.units, stockValue: stock.valueKobo / 100 }; }
function getState(user) { return { products: getProducts(), orders: getOrders(), users: getUsers(), reports: getReports(), currentUser: safeUser(user) }; }
function broadcastSale(order) { const message = `data: ${JSON.stringify({ type: 'sale', order })}\n\n`; for (const stream of adminStreams) { try { stream.write(message); } catch { adminStreams.delete(stream); } } }
function broadcastSecurity(event) { const message = `data: ${JSON.stringify(event)}\n\n`; for (const stream of securityStreams) { try { stream.write(message); } catch { securityStreams.delete(stream); } } }
function securityState() { const cutoff = Date.now() - 15 * 60 * 1000; for (const [token, session] of sessions) if (session.lastSeen < cutoff) sessions.delete(token); const events = db.prepare('SELECT event_type AS type, username, ip, user_agent AS userAgent, details, created_at AS createdAt FROM security_events ORDER BY id DESC LIMIT 100').all(); const failed = db.prepare("SELECT username, COUNT(*) AS count FROM security_events WHERE event_type = 'login_failed' GROUP BY username ORDER BY count DESC LIMIT 10").all(); return { activeVisitors: [...sessions.values()].filter(session => session.user.role !== 'Super administrator').length, activeSessions: [...sessions.values()].map(session => ({ username: session.user.username, role: session.user.role, ip: session.ip, lastSeen: new Date(session.lastSeen).toISOString() })), totalEvents: db.prepare('SELECT COUNT(*) AS count FROM security_events').get().count, failedLogins: db.prepare("SELECT COUNT(*) AS count FROM security_events WHERE event_type = 'login_failed'").get().count, successfulLogins: db.prepare("SELECT COUNT(*) AS count FROM security_events WHERE event_type = 'login_success'").get().count, failedByUsername: failed, events }; }
function isSecurityAsset(pathname) { return ['/security.html', '/security.js', '/security.css'].includes(pathname); }
function sendStatic(request, response) { const requested = new URL(request.url, `http://${request.headers.host}`).pathname; const filename = requested === '/' ? 'index.html' : requested.slice(1); const filePath = path.resolve(ROOT, filename); if (!filePath.startsWith(ROOT) || !fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) { response.writeHead(404); response.end('Not found'); return; } const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' }; response.writeHead(200, { 'Content-Type': types[path.extname(filePath)] || 'application/octet-stream' }); fs.createReadStream(filePath).pipe(response); }

async function handle(request, response) {
  const url = new URL(request.url, `http://${request.headers.host}`);
  try {
    if (request.method === 'POST' && url.pathname === '/api/login') { const body = await readBody(request); const username = String(body.username || '').trim().toLowerCase(); const user = db.prepare('SELECT * FROM users WHERE username = ?').get(username); const suppliedHash = Buffer.from(hashPassword(String(body.password || '')), 'hex'); const storedHash = user ? Buffer.from(user.password_hash, 'hex') : Buffer.alloc(0); const validPassword = storedHash.length === suppliedHash.length && crypto.timingSafeEqual(storedHash, suppliedHash); if (!user || user.status !== 'Active' || !validPassword) { recordSecurity('login_failed', request, username, user ? (user.status !== 'Active' ? 'inactive account' : 'invalid password') : 'unknown username'); return json(response, 401, { error: 'Invalid username, password, or inactive account' }); } const token = crypto.randomBytes(24).toString('hex'); sessions.set(token, { user, ip: clientIp(request), lastSeen: Date.now() }); recordSecurity('login_success', request, username, user.role); response.setHeader('Set-Cookie', `stockroom_session=${token}; HttpOnly; SameSite=Lax; Path=/`); if (user.role === 'Super administrator') return json(response, 200, { security: true, currentUser: safeUser(user) }); return json(response, 200, getState(user)); }
    if (request.method === 'POST' && url.pathname === '/api/logout') { const token = (request.headers.cookie || '').split(';').map(item => item.trim()).find(item => item.startsWith('stockroom_session='))?.split('=')[1]; const user = userFromRequest(request); if (user) recordSecurity('logout', request, user.username, user.role); if (token) sessions.delete(token); response.setHeader('Set-Cookie', 'stockroom_session=; Max-Age=0; Path=/'); return json(response, 200, { ok: true }); }
    if (request.method === 'GET' && url.pathname === '/api/events') { const user = requireUser(request, response, true); if (!user) return; response.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' }); response.write(`data: ${JSON.stringify({ type: 'connected' })}\n\n`); adminStreams.add(response); request.on('close', () => adminStreams.delete(response)); return; }
    if (request.method === 'GET' && url.pathname === '/api/security/state') { const user = requireSecurity(request, response); if (user) return json(response, 200, securityState()); }
    if (request.method === 'GET' && url.pathname === '/api/security/events') { const user = requireSecurity(request, response); if (!user) return; response.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', Connection: 'keep-alive' }); response.write(`data: ${JSON.stringify({ type: 'connected' })}\n\n`); securityStreams.add(response); request.on('close', () => securityStreams.delete(response)); return; }
    if (request.method === 'GET' && isSecurityAsset(url.pathname)) { const user = userFromRequest(request); if (user?.role !== 'Super administrator') { response.writeHead(404); response.end('Not found'); return; } return sendStatic(request, response); }
    if (request.method === 'GET' && url.pathname === '/api/state') { const user = requireUser(request, response); if (!user) return; return json(response, 200, getState(user)); }
    if (request.method === 'POST' && url.pathname === '/api/reset') { const user = requireUser(request, response, true); if (!user) return; db.exec('BEGIN'); try { db.exec('DELETE FROM order_items; DELETE FROM orders; DELETE FROM products;'); db.exec('COMMIT'); return json(response, 200, getState(user)); } catch (error) { db.exec('ROLLBACK'); return json(response, 400, { error: error.message }); } }
    if (request.method === 'POST' && url.pathname === '/api/products') { const user = requireUser(request, response, true); if (!user) return; const body = await readBody(request); db.prepare('INSERT INTO products (name, sku, category, price_kobo, stock, reorder, icon) VALUES (?, ?, ?, ?, ?, ?, ?)').run(body.name, body.sku, body.category, Math.round(Number(body.price) * 100), Number(body.stock), Number(body.reorder), body.icon); return json(response, 201, getState(user)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/products/')) { const user = requireUser(request, response, true); if (!user) return; const body = await readBody(request); db.prepare('UPDATE products SET stock = ? WHERE id = ?').run(Number(body.stock), Number(url.pathname.split('/').pop())); return json(response, 200, { ok: true }); }
    if (request.method === 'POST' && url.pathname === '/api/users') { const user = requireUser(request, response, true); if (!user) return; const body = await readBody(request); const name = String(body.name).trim(); const username = String(body.username).trim().toLowerCase(); db.prepare('INSERT INTO users (name, username, email, password_hash, role, initials, status, color) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(name, username, `${username}@stockroom.local`, hashPassword(body.password), 'Sales associate', name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase(), 'Active', '#f0b27a'); return json(response, 201, getState(user)); }
    if (request.method === 'PATCH' && url.pathname.startsWith('/api/users/')) { const user = requireUser(request, response, true); if (!user) return; const targetId = Number(url.pathname.split('/').pop()); const target = db.prepare('SELECT id, role FROM users WHERE id = ?').get(targetId); if (!target || target.role === 'Administrator' || target.id === user.id) return json(response, 400, { error: 'Only worker accounts can be deactivated.' }); const body = await readBody(request); db.prepare('UPDATE users SET status = ? WHERE id = ?').run(body.status === 'Inactive' ? 'Inactive' : 'Active', targetId); return json(response, 200, { ok: true }); }
    if (request.method === 'POST' && url.pathname === '/api/orders') { const user = requireUser(request, response); if (!user) return; const body = await readBody(request); const items = body.items || []; db.exec('BEGIN'); try { let totalKobo = 0; for (const item of items) { const row = db.prepare('SELECT stock, price_kobo FROM products WHERE id = ?').get(Number(item.productId)); if (!row || row.stock < Number(item.quantity)) throw new Error('Insufficient stock'); totalKobo += row.price_kobo * Number(item.quantity); } const next = db.prepare('SELECT COUNT(*) AS count FROM orders').get().count + 1049; const orderResult = db.prepare('INSERT INTO orders (order_number, created_at, customer, staff_user_id, payment, total_kobo) VALUES (?, ?, ?, ?, ?, ?)').run(`ORD-${next}`, new Date().toISOString(), body.customer || 'Walk-in customer', user.id, body.payment, totalKobo); const addItem = db.prepare('INSERT INTO order_items (order_id, product_id, quantity, unit_price_kobo) VALUES (?, ?, ?, ?)'); const reduce = db.prepare('UPDATE products SET stock = stock - ? WHERE id = ?'); for (const item of items) { const current = db.prepare('SELECT price_kobo FROM products WHERE id = ?').get(Number(item.productId)); addItem.run(Number(orderResult.lastInsertRowid), Number(item.productId), Number(item.quantity), current.price_kobo); reduce.run(Number(item.quantity), Number(item.productId)); } db.exec('COMMIT'); const createdOrder = getOrders()[0]; broadcastSale(createdOrder); return json(response, 201, getState(user)); } catch (error) { db.exec('ROLLBACK'); return json(response, 400, { error: error.message }); } }
    return sendStatic(request, response);
  } catch (error) { console.error(error); return json(response, 500, { error: error.message }); }
}

initializeDatabase();
http.createServer(handle).listen(PORT, () => console.log(`Stockroom running at http://localhost:${PORT}`));
